### ISSUE TITLE
`log10` causes assertion to fail

### ISSUE THREAD

**Issue by jberling** [mgriebling/BigDecimal#4]
When I call log10 with some values, an assertion fails at BigDecimal/BigDecimal.swift:1118.

Example:

```Swift
_ = BigDecimal.log10(BigDecimal(10.01))
```

**Comment by manhphi65** [comment]
I haven't checked the logic thoroughly, but there is a simple way to fix your error using the BigDecimal(_:String) constructor or adjusting the precision of the BigDecimal(_:Double) initializer.
Code :
`_ = BigDecimal.log10(BigDecimal("10.01"))`
`_ = BigDecimal.log10(BigDecimal(10.01).round(Rounding(.toNearestOrAwayFromZero, 10)))`

The BigDecimal(_:Double) constructor will not properly display the value you enter, due to the floating point of Double. It will result like this:
`BigDecimal(10.01).asString()` print -> 10.0099999999999997868371792719699442386627197265625

**Comment by jberling** [comment]
Thanks! I understand why Double can't represent 10.01 exactly, but I don't understand why this result in the assertion error. I lack the necessary knowledge. 

They way I understand it, the BigDecimal constructor would result in a value equal to the Double represented by the 10.1 literal. And why should that result in the assertion error? What am I missing?

**Comment by manhphi65** [comment]
I just took a look at the log10 calculation algorithm. And it seems like this algorithm in Java/Kotlin:

**Comment by manhphi65** [comment]
Have you fixed the above problem yet? I just took a look at the log10 calculation algorithm. And it seems like this algorithm in Java/Kotlin:
[big-math](https://github.com/eobermuhlner/big-math/blob/b659e2f6f3f79a64d6d587c0876dac5e06870012/ch.obermuhlner.math.big/src/main/java/ch/obermuhlner/math/big/BigDecimalMath.java#L1012)
I see the problem: calculating the mantissa is wrong.
`let mantissa = x.significand`
For numbers with many digits (Double), the significand is not a mantissa. Leading to the calculation formula being divided by 0, and causing the error as you mentioned.
Mantissa must be calculated according to the following command:
`let mantissa = x.significand.scale(-x.precision+1)`
But when I adjusted it, I still didn't see it running correctly. There may be many more miscalculations. When I have time to correct it and push it to my fork

**Comment by manhphi65** [comment]
Fixed : https://github.com/mgriebling/BigDecimal/pull/3/commits/adbf2e615edcfaea50b6d9bb9305438059c9187a

**Comment by mgriebling** [comment]
Can you add a pull request to merge with the original code?

**Comment by manhphi65** [comment]
> Can you add a pull request to merge with the original code?
I included that commit in a pull request, and you merged it.
> Fixed : [adbf2e6](https://github.com/mgriebling/BigDecimal/commit/adbf2e615edcfaea50b6d9bb9305438059c9187a)
